### ISSUE TITLE
Cannot inject grammar into already embedded languages

### ISSUE THREAD

**Issue by NTaylorMullen** [microsoft/vscode-textmate#122]
I'm writing a language grammar for Razor and throughout Razor there are several [locations ](https://github.com/aspnet/AspNetCore-Tooling/blob/c7815ea4f2e52697d621b32c013b0ae7cc9544ec/src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml#L45) where we call through to C#'s grammar to run their rules. However, after having attempted to write an injection grammar to handle cases when Razor weaves HTML into specific C# constructs aka:

![image](https://user-images.githubusercontent.com/2008729/70841382-e0c9a000-1dce-11ea-9e9c-af2a642c1b75.png)

It doesn't seem like injecting code into the `source.cs` grammar is sufficient. For my injection grammar I've written:
```YAML
name: ASP.NET Razor C# Injection
scopeName: 'text.aspnetcorerazor.injection'
injectionSelector: 'L:source.cs'
patterns:
  - include: '#razor-template'

repository:
  razor-template:
    name: 'meta.structure.template.razor'
    begin: '(@)(?=\<)'
    beginCaptures:
      1: { patterns: [ include: 'text.aspnetcorerazor#transition' ] }
    patterns:
      - include: 'text.aspnetcorerazor#wellformed-html'
    end: '(?<=\>)'
```

Along side:
![image](https://user-images.githubusercontent.com/2008729/70841461-83821e80-1dcf-11ea-96d0-5b54efa0c066.png)

Which works fine in .cs files (haven't restricted where it can run yet):
![image](https://user-images.githubusercontent.com/2008729/70841429-37cf7500-1dcf-11ea-8446-86490a491ebd.png)

However, when trying to make use of the injection in a Razor file in the embedded C#, it doesn't seem to apply:
![image](https://user-images.githubusercontent.com/2008729/70841439-56ce0700-1dcf-11ea-9e8a-d06cb843821e.png)
