### ISSUE TITLE
Repository works only when it defined at top level of grammar file

### ISSUE THREAD

**Issue by graceful-potato** [microsoft/vscode-textmate#140]
In textmate you can define repositroy within a specific rule and it works fine.

I created this grammar file for test
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>qwe</string>
	</array>
	<key>name</key>
	<string>Qwe</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>begin</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.begin.qwe</string>
				</dict>
			</dict>
			<key>end</key>
			<string>end</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.qwe</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.begin-end.qwe</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#foo</string>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>foo</key>
				<dict>
					<key>match</key>
					<string>foo</string>
					<key>name</key>
					<string>keyword.control.foo.qwe</string>
				</dict>
			</dict>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.qwe</string>
	<key>uuid</key>
	<string>06AD8311-7342-4086-843E-BFB83EBC2377</string>
</dict>
</plist>
```

result in textmate:
![Screen Shot 2020-10-05 at 10 30 28](https://user-images.githubusercontent.com/56965223/95253076-8cdceb80-0826-11eb-80a9-fb33bea79805.png)
result in vscode:
![Screenshot from 2020-10-06 22-50-26](https://user-images.githubusercontent.com/56965223/95253098-9403f980-0826-11eb-9bcb-b72c62968390.png)

In vscode whole rule stopped working without any error

**Comment by msftrncs** [comment]
I have used sub `repository` several times.  My current experience says that it needs to reside in the root element,  or directly in other repositories, in order to work, not within any `patterns` element.   It is possible that TextMate allows `repository` to appear anywhere, but it is not documented.

**Comment by jtbandes** [comment]
+1! This was a tough one to debug! 😬 

I believe I am running into the same issue. As a reduced test case I defined this simple grammar:

```yaml
patterns:
  - include: "#aaaaaa"

repository:
  aaaaaa:
    name: meta.definition.operator.swift
    begin: abc
    end: $
    beginCaptures:
      0: { name: storage.modifier.swift }
    patterns:
      - include: "#xxx"

    repository:
      xxx:
        match: def
        captures:
          0: { name: entity.name.function.operator.swift }
```

In TextMate this renders as expected:

<img width="137" alt="image" src="https://github.com/microsoft/vscode-textmate/assets/14237/dca3ed1a-fdd2-47a8-aa6c-3b98349666c5">

In VS Code, somehow even the `name` and `beginCaptures` are not applied. It's like the whole pattern is being thrown away.

<img width="405" alt="image" src="https://github.com/microsoft/vscode-textmate/assets/14237/864a7d29-cbde-434f-8d8c-8d9b61087206">

If I change it to:


```yaml
patterns:
  - include: "#aaaaaa"

repository:
  aaaaaa:
    ...
  xxx:
    ...
```

then it seems to work.


Would you agree this looks like the same issue, or do you think it's a different one?

**Comment by graceful-potato** [comment]
@jtbandes looks like the very same issue. Rule stops working when you define repository in this rule and include it

**Comment by RedCMD** [comment]
@jtbandes also keep in mind another bug
if all `include`s inside the `patterns` cannot be found
then the entire `repository` item `aaaaaa` will fail and be skipped

an empty `patterns` array or having atleast one working `include` inside it will not cause an error, and allow it to work as expected

**Comment by jtbandes** [comment]
Thanks for the info. I've also noticed another bug which is causing some grief: a 2nd match of a group (e.g. via `\g<1>`) will cancel/override an earlier match:

```
  - match: (AAA)\g<1>
    captures:
      1: { name: keyword.control }
```

produces: <img width="61" alt="image" src="https://github.com/microsoft/vscode-textmate/assets/14237/87d3287d-9370-4a70-a186-5c0297887a1f">

This seems related to https://github.com/microsoft/vscode-textmate/issues/164 but I'm not sure it's the same issue.

**Comment by jtbandes** [comment]
Also, patterns executed inside a capture group seem to override scopes from parent groups:

```yaml
  - match: (A(BCD+EF)G)
    captures:
      1:
        name: keyword.control
      2:
        patterns:
          - match: CDE
            name: storage.modifier
```

produces: <img width="68" alt="image" src="https://github.com/microsoft/vscode-textmate/assets/14237/f7d2d504-b5ff-4c8f-8c2b-8f9c154f8324">
