### ISSUE TITLE
yaml highlighting/textmate recognises some integers as strings (or vice versa?)

### ISSUE THREAD

**Issue by pedroterzero** [microsoft/vscode-textmate#168]
Some integers (or strings?) are treated differently even though they look the same to me.

In each comment I've specified what the scope inspector reports the scope as.

Testcase:
```yaml
test:
  - test: 01 # constant.numeric.integer.yaml
  - test: 02 # constant.numeric.integer.yaml
  - test: 03 # constant.numeric.integer.yaml
  - test: 04 # constant.numeric.integer.yaml
  - test: 05 # constant.numeric.integer.yaml
  - test: 06 # constant.numeric.integer.yaml
  - test: 07 # constant.numeric.integer.yaml
  - test: 08 # string.unquoted.plain.out.yaml
  - test: 09 # string.unquoted.plain.out.yaml
  - test: 10 # constant.numeric.integer.yaml
```

This is what it ends up looking like for me:
![Screenshot from 2022-02-17 19-34-06](https://user-images.githubusercontent.com/72469659/154547883-d7872a55-9ed8-4e25-8820-2c32019183c6.png)

I'd expect them all to be the same; so either they should all be integers or they should all be unquoted strings. Right?
